@extends(auth()->user()?->isSuperAdmin() ? 'layouts.super-admin' : 'layouts.admin')
@section('title', 'Yêu cầu hỗ trợ đơn')
@section('content')
@php
    $types = ['missing_item' => 'Thiếu món', 'wrong_item' => 'Sai món', 'quality_issue' => 'Chất lượng đồ uống', 'refund_request' => 'Yêu cầu hoàn tiền', 'other' => 'Vấn đề khác'];
    $statuses = ['open' => ['Đang chờ', 'warning'], 'processing' => ['Đang kiểm tra', 'primary'], 'approved' => ['Đã duyệt hỗ trợ', 'info'], 'remedy_in_progress' => ['Đang khắc phục', 'primary'], 'awaiting_customer' => ['Chờ khách xác nhận', 'warning'], 'resolved' => ['Hoàn tất', 'success'], 'rejected' => ['Từ chối', 'danger']];
    $nextStatuses = ['open' => ['open', 'processing', 'rejected'], 'processing' => ['processing', 'approved', 'rejected'], 'approved' => ['approved', 'remedy_in_progress', 'rejected'], 'remedy_in_progress' => ['remedy_in_progress', 'awaiting_customer'], 'awaiting_customer' => ['awaiting_customer', 'resolved'], 'resolved' => ['resolved'], 'rejected' => ['rejected']];
@endphp
<style>
    .issue-board{max-width:1320px;margin:auto}.issue-card{background:#fff;border:1px solid #e1ebe7;border-radius:16px;padding:18px;margin-bottom:14px;box-shadow:0 5px 18px rgba(18,66,52,.04)}.issue-grid{display:grid;grid-template-columns:1.15fr 1fr 1.25fr 360px;gap:18px;align-items:start}.issue-label{font-size:.72rem;letter-spacing:.04em;color:#71817b;text-transform:uppercase;font-weight:800;margin-bottom:6px}.issue-value{font-size:1rem;font-weight:750;color:#16231f}.issue-meta{font-size:.88rem;color:#65756f;margin-top:5px}.order-box,.issue-desc,.issue-action{border:1px solid #e1ece8;background:#f8fbfa;border-radius:12px}.order-box{margin-top:12px;padding:10px 12px}.order-row{display:flex;justify-content:space-between;gap:8px;padding:7px 0;border-bottom:1px dashed #d7e7e1;font-size:.88rem}.order-row:last-of-type{border-bottom:0}.order-row .muted{font-size:.78rem;color:#70817a}.order-total{display:flex;justify-content:space-between;padding-top:9px;margin-top:2px;border-top:1px solid #dceae5;font-weight:800}.issue-desc{padding:12px;line-height:1.5;min-height:64px}.issue-evidence{display:inline-flex;align-items:center;gap:6px;margin-top:10px;color:#008b70;font-weight:700;text-decoration:none}.issue-action{padding:13px}.issue-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.issue-action select,.issue-action input{border-radius:9px;font-size:.88rem}.issue-action .full{grid-column:1/-1}.issue-help{font-size:.78rem;color:#6b7b75;line-height:1.35}.issue-help.primary{color:#008b70}.issue-action button{margin-top:10px}@media(max-width:1150px){.issue-grid{grid-template-columns:repeat(2,1fr)}.issue-action{grid-column:span 2}}@media(max-width:680px){.issue-grid,.issue-form-grid{grid-template-columns:1fr}.issue-action{grid-column:auto}.issue-action .full{grid-column:auto}}
    .order-box{max-height:none;overflow:visible}.order-total{position:static;background:transparent}.order-more{border:0;background:transparent;color:#008b70;font-size:.82rem;font-weight:700;padding:7px 0 2px;cursor:pointer}
</style>
<div class="container-fluid py-4 issue-board">
    <div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><p class="text-primary fw-semibold mb-1">CHĂM SÓC KHÁCH HÀNG</p><h1 class="h3 fw-bold mb-1">Yêu cầu hỗ trợ đơn</h1><p class="text-secondary mb-0">Kiểm tra đơn, chọn quyền lợi và theo dõi phản hồi của khách.</p></div><span class="badge rounded-pill text-bg-primary px-3 py-2">{{ $reports->total() }} yêu cầu</span></div>
    @if(session('success'))<div class="alert alert-success border-0 rounded-4">{{ session('success') }}</div>@endif
    @forelse($reports as $issue)
        @php [$statusLabel, $statusColor] = $statuses[$issue->status] ?? ['Đang chờ', 'secondary']; $availableStatuses = $nextStatuses[$issue->status] ?? [$issue->status]; @endphp
        <article class="issue-card"><div class="issue-grid">
            <section><div class="issue-label">Đơn hàng</div><div class="issue-value">{{ $issue->order->order_code ?? '#'.$issue->order_id }}</div><div class="issue-meta"><i class="bi bi-shop me-1"></i>{{ $issue->order->branch?->name ?? 'Chưa xác định chi nhánh' }}</div><div class="issue-meta"><i class="bi bi-credit-card me-1"></i><strong>{{ $issue->order->payment_method === 'vnpay' ? 'VNPay' : 'Tiền mặt (COD)' }}</strong> · {{ $issue->order->payment_status === 'paid' ? 'Đã thanh toán' : 'Chưa thanh toán' }}</div>@if($issue->order->payment_method === 'vnpay' && $issue->order->vnpay_transaction_id)<div class="issue-meta">Mã GD: {{ $issue->order->vnpay_transaction_id }}</div>@endif<div class="issue-meta"><i class="bi bi-clock me-1"></i>{{ $issue->created_at->format('d/m/Y H:i') }}</div><div class="order-box"><div class="issue-label">Món trong đơn</div>@forelse($issue->order->orderItems as $item)<div class="order-row"><div><strong>{{ $item->quantity }}× {{ $item->product?->name ?? 'Sản phẩm đã xoá' }}</strong><div class="muted">{{ $item->productSize?->size_name ?? $item->productSize?->name ?? '' }}{{ $item->sugar_level !== null ? ' · Đường '.$item->sugar_level.'%' : '' }}{{ $item->ice_level !== null ? ' · Đá '.$item->ice_level.'%' : '' }}</div></div><strong>{{ number_format((int) $item->getSubtotal(), 0, ',', '.') }}đ</strong></div>@empty<div class="issue-meta">Không tìm thấy món trong đơn.</div>@endforelse<div class="order-total"><span>Tổng đơn</span><span class="text-primary">{{ number_format((int) $issue->order->total, 0, ',', '.') }}đ</span></div></div></section>
            <section><div class="issue-label">Khách hàng</div><div class="issue-value">{{ $issue->user->name }}</div><div class="issue-meta">{{ $issue->user->email }}</div><span class="badge text-bg-{{ $statusColor }} mt-3">{{ $statusLabel }}</span></section>
            <section><div class="issue-label">{{ $types[$issue->type] ?? 'Vấn đề khác' }}</div><div class="issue-desc">{{ $issue->description }}</div>@php($evidenceCount = count($issue->evidence_files ?? ($issue->evidence_path ? [['path' => $issue->evidence_path]] : [])))@if($evidenceCount)<div class="d-flex flex-wrap gap-2 mt-2">@for($fileIndex = 0; $fileIndex < $evidenceCount; $fileIndex++)<a class="issue-evidence mt-0" href="{{ route('admin.order-issues.evidence', ['issue' => $issue, 'file' => $fileIndex]) }}" target="_blank"><i class="bi bi-image"></i>Ảnh {{ $fileIndex + 1 }}</a>@endfor</div>@endif</section>
            <form class="issue-action" method="POST" action="{{ route('admin.order-issues.update', $issue) }}" data-order-total="{{ (int) $issue->order->total }}" data-voucher-issued="{{ $issue->voucher_coupon_id ? '1' : '0' }}">@csrf @method('PATCH')<div class="issue-label">Phương án hỗ trợ</div><div class="issue-form-grid"><select name="status" class="form-select">@foreach($availableStatuses as $availableStatus)<option value="{{ $availableStatus }}" @selected($issue->status === $availableStatus)>{{ $statuses[$availableStatus][0] }}</option>@endforeach</select><select name="resolution_type" class="form-select js-resolution-type"><option value="">Chọn cách hỗ trợ</option><option value="redelivery" @selected($issue->resolution_type==='redelivery')>Giao bù / đổi món</option><option value="refund" @selected($issue->resolution_type==='refund')>{{ $issue->order->payment_method === 'vnpay' && $issue->order->payment_status === 'paid' ? 'Hoàn về VNPay' : 'Hoàn tiền thủ công' }}</option><option value="voucher" @selected($issue->resolution_type==='voucher')>Voucher toàn bộ đơn</option><option value="other" @selected($issue->resolution_type==='other')>Phương án khác</option></select><input name="resolution_value" class="form-control full js-resolution-value" value="{{ $issue->resolution_value }}" placeholder="Số tiền hoặc nội dung hỗ trợ"><div class="issue-help primary full js-voucher-hint d-none"><i class="bi bi-lightning-charge-fill me-1"></i>Voucher tự lấy toàn bộ tổng tiền đơn.</div><input type="datetime-local" name="estimated_at" min="{{ now()->format('Y-m-d\\TH:i') }}" class="form-control" value="{{ $issue->estimated_at?->format('Y-m-d\\TH:i') }}"><input name="admin_note" class="form-control" value="{{ $issue->admin_note }}" placeholder="Phản hồi cho khách"></div><div class="issue-help mt-2">Voucher cấp thẳng vào tài khoản; đơn VNPay ghi nhận yêu cầu hoàn về VNPay.</div><button class="btn btn-primary btn-sm w-100 rounded-pill"><i class="bi bi-check2-circle me-1"></i>Lưu phương án</button></form>
        </div></article>
    @empty
        <div class="text-center bg-white border rounded-4 py-5 text-secondary"><i class="bi bi-inbox fs-2 d-block mb-2"></i>Chưa có yêu cầu hỗ trợ.</div>
    @endforelse
    <div class="mt-3">{{ $reports->links() }}</div>
</div>
<script>
document.querySelectorAll('.issue-action').forEach((form) => { const type=form.querySelector('.js-resolution-type'),value=form.querySelector('.js-resolution-value'),hint=form.querySelector('.js-voucher-hint'); const sync=()=>{const voucher=type.value==='voucher';hint.classList.toggle('d-none',!voucher);value.readOnly=voucher;if(voucher&&form.dataset.voucherIssued!=='1')value.value=`${Number(form.dataset.orderTotal||0).toLocaleString('vi-VN')}đ (toàn bộ giá trị đơn)`}; type.addEventListener('change',sync);sync(); });
document.querySelectorAll('.order-box').forEach((box) => { const rows=[...box.querySelectorAll('.order-row')]; if(rows.length<=2)return; rows.slice(2).forEach((row)=>row.hidden=true); const button=document.createElement('button'); button.type='button'; button.className='order-more'; button.textContent=`Xem thêm ${rows.length-2} món`; button.addEventListener('click',()=>{const expanded=button.dataset.expanded==='1'; rows.slice(2).forEach((row)=>row.hidden=expanded); button.dataset.expanded=expanded?'0':'1'; button.textContent=expanded?`Xem thêm ${rows.length-2} món`:'Thu gọn danh sách';}); box.querySelector('.order-total').before(button); });
</script>
@endsection
